package org.entity.test;
/**
  * This entity class is Generated by freemarker;
  */
public class Entity{
	private String id;
	private String name;
	private String sex;

	public String getId(){
		return id;
	};
	public void setId(String id){
		this.id=id;
	};
	public String getName(){
		return name;
	};
	public void setName(String name){
		this.name=name;
	};
	public String getSex(){
		return sex;
	};
	public void setSex(String sex){
		this.sex=sex;
	};
}