package org.entity.test;
import java.sql.Date;
/**
  * This entity class is Generated by freemarker;
  */
public class Entity{
	private int id;
	private String user_name;
	private String password;
	private String address;
	private String phone_number;
	private Date create_time;
	private Date update_time;

	public int getId(){
		return id;
	};
	public void setId(int id){
		this.id=id;
	};
	public String getUser_name(){
		return user_name;
	};
	public void setUser_name(String user_name){
		this.user_name=user_name;
	};
	public String getPassword(){
		return password;
	};
	public void setPassword(String password){
		this.password=password;
	};
	public String getAddress(){
		return address;
	};
	public void setAddress(String address){
		this.address=address;
	};
	public String getPhone_number(){
		return phone_number;
	};
	public void setPhone_number(String phone_number){
		this.phone_number=phone_number;
	};
	public Date getCreate_time(){
		return create_time;
	};
	public void setCreate_time(Date create_time){
		this.create_time=create_time;
	};
	public Date getUpdate_time(){
		return update_time;
	};
	public void setUpdate_time(Date update_time){
		this.update_time=update_time;
	};
}